name: pipeline-master
on:
  push:
    branches:
      - 'master'

jobs:
  checking_template_update:
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed
      run: |
        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD
        # Check if a file under "projects/templates/" or with the .txt extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match '^projects/templates/' -or $_ -match '.txt$' }
        $HasDiff = $SourceDiff.Length -gt 0
        # Set the output named "docs_changed"
        Write-Host "::set-output name=docs_changed::$HasDiff"
  # Run the job only with "docs_changed" equals "True"
  install_dependencies:
    runs-on: 'ubuntu-20.04'
    needs: [ checking_template_update ]
    if: needs.checking_template_update.outputs.docs_changed == 'True'
    steps:
    - user: convictional/trigger-workflow-and-wait@v1.3.0
      with:
        owner: Natannegara
        repo: config-management
        github_token: ${{ secrets.REPO_TOKEN }}
        workflow_file_name: config-management.yml
        ref: master
    - name: Trigger to Ansible
      run: |
        echo "succesfuly triggered"