name: pipeline-master
on:
  push:
    branches:
      - 'master'

jobs:
  checking_template_update:
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: bash
      id: check_file_changed
      name: Check for any updates in projects folder
      run: |

        if [[ $(echo $(git diff --name-only HEAD^ HEAD projects/) | wc -w) > 0 ]]; then
          echo "::set-output name=docs_changed::True"
          exit 0
        else
          echo "::set-output name=docs_changed::False"
          echo  0
        fi

  send_venv:
    runs-on: 'ubuntu-20.04'
    needs: [ checking_template_update ]
    if: needs.checking_template_update.outputs.docs_changed == 'True'
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      name: Triggering to Ansible
      with:
        owner: personal-natan
        repo: config-management
        github_token: ${{ secrets.REPO_TOKEN }}
        workflow_file_name: config-management.yml
        ref: master

