name: pipeline-master
on:
  push:
    branches:
      - 'master'

jobs:
  checking_template_update:
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: bash
      id: check_file_changed
      name: Check for any updates in projects folder
      run: |
        export diff=$(git diff --name-only HEAD^ HEAD)
        export updated="projects/"

        for i in $diff; do
          if [[ "$i" == "$updated"* ]]; then
            echo "::set-output name=docs_changed::True"
            exit 0
          else
            echo $i
          fi
        done

  print-output:
    runs-on: 'ubuntu-20.04'
    needs: [ checking_template_update ] 
    if: needs.checking_template_update.outputs.docs_changed == 'True'
    steps:
    - run: |
          echo ${{ needs.checking_template_update.outputs.docs_changed }}
      name: Check Output
    
  # push_templates:
  #   runs-on: 'ubuntu-20.04'
  #   needs: [ checking_template_update ]
  #   if: needs.checking_template_update.outputs.docs_changed == 'True'
  #   steps:
  #   - uses: andstor/copycat-action@v3
  #     name: Push templates to ansbile repository
  #     with:
  #       personal_token: ${{ secrets.REPO_TOKEN }}
  #       src_path: projects/templates/
  #       dst_path: roles/install-dep/
  #       dst_owner: Natannegara
  #       dst_repo_name: config-management

  # push_vars:
  #   runs-on: 'ubuntu-20.04'
  #   needs: [ push_templates ]
  #   if: needs.checking_template_update.outputs.docs_changed == 'True'
  #   steps:        
  #   - uses: andstor/copycat-action@v3
  #     name: Push target to ansbile repository
  #     with:
  #       personal_token: ${{ secrets.REPO_TOKEN }}
  #       src_path: projects/vars/
  #       dst_path: roles/install-dep/
  #       dst_owner: Natannegara
  #       dst_repo_name: config-management

  # trigger_ansible:
  #   runs-on: 'ubuntu-20.04'
  #   needs: [ push_vars ]
  #   if: needs.checking_template_update.outputs.docs_changed == 'True'
  #   steps:         
  #   - uses: convictional/trigger-workflow-and-wait@v1.3.0
  #     with:
  #       owner: Natannegara
  #       repo: config-management
  #       github_token: ${{ secrets.REPO_TOKEN }}
  #       workflow_file_name: config-management.yml
  #       ref: master
