name: pipeline-master
on:
  push:
    branches:
      - 'master'

jobs:
  checking_template_update:
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: bash
      id: check_file_changed
      name: Check for any updates in projects folder
      run: |
        export diff=$(git diff --name-only HEAD^ HEAD)
        export updated="projects/"

        for i in $diff; do
          if [[ "$i" == "$updated"* ]]; then
            echo "::set-output name=docs_changed::True"
            exit 0
          else
            echo $i
          fi
        done
    
  send_venv:
    runs-on: 'ubuntu-20.04'
    needs: [ checking_template_update ]
    # if: needs.checking_template_update.outputs.docs_changed == 'True'
    steps:
    - name: Save current directory
      uses: actions/checkout@v3
      with:
        path: 'src'
        ref: master
        persist-credentials: false
    
    - name: Get ansible directory
      uses: actions/checkout@v3
      with:
        path: 'dest'
        ref: master
        persist-credentials: true
        repository: 'Natannegara/config-management'
        token: '${{ secrets.REPO_TOKEN }}'
        fetch-depth: 0
    
    - name: copy src to dest
      run: |
        mkdir -p dest/config-management/test
        cp -rvT src/projects dest/config-management/test
        echo dest
        ls dest
        echo src
        ls src/projects
        

    # - uses: convictional/trigger-workflow-and-wait@v1.3.0
    #   name: Triggering to Ansible
    #   with:
    #     owner: Natannegara
    #     repo: config-management
    #     github_token: ${{ secrets.REPO_TOKEN }}
    #     workflow_file_name: config-management.yml
    #     ref: master      
    
