name: pipeline-master
on:
  push:
    branches:
      - 'master'

jobs:
  checking_template_update:
    runs-on: 'ubuntu-20.04'
    # Declare outputs for next jobs
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: bash
      id: check_file_changed
      name: Check for any updates in projects folder
      run: |
        export diff=$(git diff --name-only HEAD^ HEAD)
        export updated="projects/"

        for i in $diff; do
          if [[ "$i" == "$updated"* ]]; then
            echo "::set-output name=docs_changed::True"
            exit 0
          else
            echo $i
          fi
        done

  send_venv:
    runs-on: 'ubuntu-20.04'
    needs: [ checking_template_update ]
    # if: needs.checking_template_update.outputs.docs_changed == 'True'
    steps:
    - name: Save current directory
      uses: actions/checkout@v3
      with:
        path: 'src'
        ref: master
        persist-credentials: false
    
    - run: mkdir -p clone-folder
      shell: bash

    - name: Check an Update
      id: newFiles
      working-directory: clone-folder
      shell: bash
      run: |
        git clone https://${{secrets.REPO_TOKEN}}@github.com/Natannegara/config-management
        # git config --global user.name "${{ secrets.RUNNER_USER }}"
        # git config --global user.email "${{ secrets.RUNNER_EMAIL }}"
        # git commit -m "maint: New Update ${{ github.event }}"
        # git config --global credential.helper cache
        
        rm config-management/roles/install-dep/templates/*
        cp -r ../src/projects/* config-management/roles/install-dep/templates
        ls config-management/roles/install-dep/templates

    # - uses: convictional/trigger-workflow-and-wait@v1.3.0
    #   name: Triggering to Ansible
    #   with:
    #     owner: Natannegara
    #     repo: config-management
    #     github_token: ${{ secrets.REPO_TOKEN }}
    #     workflow_file_name: config-management.yml
    #     ref: master

